# This is an introduction to scikit learn

### What we are going to learn

1. An end-to-end workflow
2. getting the data ready
3. choosing the right estimator/Algorithm for our problems
4. Fit the model/Algorithm and use it to make prediction of our data
5. Evaluating a model
6. Improve a model
7. Save and load a trained model
8. Putting it all together

### 1. An end-to-end workflow

In [1]:
import pandas as pd

heart_disease = pd.read_csv("heart-disease.csv")
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [2]:
# 2. Getting the data ready
# Setting the feachures matrix
x = heart_disease.drop(["target"], axis=1)
# setting the labels
y = heart_disease["target"]

In [3]:
# 3. Choosing the right estimator/Algorithm 
from sklearn.ensemble import RandomForestClassifier # It's a classification model
clf = RandomForestClassifier()

# We'll keep the default hyperparams
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [4]:
# 4. Fit the model with the data
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2);

In [5]:
clf.fit(x_train, y_train);

In [6]:
y_preds = clf.predict(x_test)
y_preds

array([0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0])

In [7]:
y_test

34     1
32     1
66     1
209    0
0      1
      ..
57     1
141    1
169    0
226    0
138    1
Name: target, Length: 61, dtype: int64

In [8]:
clf.score(x_train, y_train)*100

100.0

In [9]:
clf.score(x_test, y_test) * 100

88.52459016393442

### 5. Evaluating the model

In [10]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.79      0.96      0.86        23
           1       0.97      0.84      0.90        38

    accuracy                           0.89        61
   macro avg       0.88      0.90      0.88        61
weighted avg       0.90      0.89      0.89        61

In [11]:
confusion_matrix(y_test, y_preds)

array([[22,  1],
       [ 6, 32]])

In [12]:
accuracy_score(y_test, y_preds)

0.8852459016393442

In [13]:
# 6. Improve the model
import numpy as np
np.random.seed(42);
for i in range(10,100,10):
    print(f"The model prediction in: {i} estimator")
    clf = RandomForestClassifier(n_estimators=i).fit(x_train, y_train)
    print(f"Model accuracy on test set is: {clf.score(x_test, y_test)*100:.2f}%")
    print("")

The model prediction in: 10 estimator
Model accuracy on test set is: 81.97%

The model prediction in: 20 estimator
Model accuracy on test set is: 77.05%

The model prediction in: 30 estimator
Model accuracy on test set is: 85.25%

The model prediction in: 40 estimator
Model accuracy on test set is: 88.52%

The model prediction in: 50 estimator
Model accuracy on test set is: 88.52%

The model prediction in: 60 estimator
Model accuracy on test set is: 85.25%

The model prediction in: 70 estimator
Model accuracy on test set is: 86.89%

The model prediction in: 80 estimator
Model accuracy on test set is: 88.52%

The model prediction in: 90 estimator
Model accuracy on test set is: 86.89%

In [14]:
# 7. Save the model
import pickle

pickle.dump(clf, open("random_forest_model1.pkl", "wb"))

In [15]:
loaded_model = pickle.load(open("random_forest_model1.pkl", "rb"))
loaded_model.score(x_test, y_test)

0.8688524590163934

## 1. Getting our data ready.
    There are three main thing we have to cover:
        * Splitting the data into (Features & Labels) or (X and Y)
        * Filling (also called imputing) or disregarding missing values
        * Converting non numerical values to numerical values (also called feature encoding)

In [16]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [17]:
# Let's construct the features and labels
x = heart_disease.drop(["target"], axis=1) # setting the x-features
# Now labels
y = heart_disease["target"]

In [18]:
x.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [19]:
# Now it's time to split data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [20]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [21]:
x.shape

(303, 13)

In [22]:
303*0.8

242.4

In [23]:
242+61

303

## Transforming our data to numerical values
    * We can do this in many different ways:
        1. Using sklearn librearies
        2. Using numpy

In [24]:
car_sales = pd.read_csv("data/car-sales-extended.csv")
car_sales.head()

     Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [25]:
car_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           1000 non-null   str
 1   Colour         1000 non-null   str
 2   Odometer (KM)  1000 non-null   int64
 3   Doors          1000 non-null   int64
 4   Price          1000 non-null   int64
dtypes: int64(3), str(2)
memory usage: 39.2 KB

In [26]:
## Now Let's try to split this data to features and labels
X = car_sales.drop("Price", axis=1)
Y = car_sales["Price"]

In [27]:
# Now our usewall work we have to convert the values to numerical values
# Let's use one-hot-encoding to convert our string's to numerical values.
X_transformed = pd.get_dummies(X, columns=["Make", "Colour", "Doors"], dtype=int)
X_transformed.head()

,Odometer (KM),Make_BMW,Make_Honda,Make_Nissan,Make_Toyota,Colour_Black,Colour_Blue,Colour_Green,Colour_Red,Colour_White,Doors_3,Doors_4,Doors_5
0,35431,0,1,0,0,0,0,0,0,1,0,1,0
1,192714,1,0,0,0,0,1,0,0,0,0,0,1
2,84714,0,1,0,0,0,0,0,0,1,0,1,0
3,154365,0,0,0,1,0,0,0,0,1,0,1,0
4,181577,0,0,1,0,0,1,0,0,0,1,0,0

In [28]:
X_transformed.shape, X_transformed.size

((1000, 13), 13000)

In [29]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X_transformed, Y, test_size=0.2)

In [30]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((800, 13), (200, 13), (800,), (200,))

In [31]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train, y_train);

In [32]:
model.score(x_test, y_test)*100

19.72335129480527

## Now it's time to learn how to deal with data with missing values

- First we have to fill the missing data with relevant data (FEATURES)
- If the missing data belongs to (LABELS), then we have to remove those missing data's

In [33]:
car_sales_missing = pd.read_csv("data/car-sales-extended-missing-data.csv")
car_sales_missing.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [34]:
# Now we have to see how many missing data's are there in our database
car_sales_missing.isna().sum() # So, this will give all the columns with missing values

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

### So on average we have 50 missing values in each columns
    1. Now if we want to convert those `String values` to numbers, it will throw error
    2. So, first we have to deal with the missing values of each column

In [35]:
car_sales_missing["Odometer (KM)"].mean()

np.float64(131253.23789473684)

In [36]:
# Let's fill the missing values of make with missing. As this is not a numerical column
# car_sales_missing["Make"].fillna("missing", inplace=True) #it never work's anymore

car_sales_missing.fillna({"Make": "missing"}, inplace=True)

car_sales_missing.fillna({"Colour": "missing"}, inplace=True)

car_sales_missing.fillna({"Odometer (KM)": car_sales_missing["Odometer (KM)"].mean()},inplace=True)

car_sales_missing.fillna({"Doors": 4}, inplace=True)

        Make Colour  Odometer (KM)  Doors    Price
0      Honda  White        35431.0    4.0  15323.0
1        BMW   Blue       192714.0    5.0  19943.0
2      Honda  White        84714.0    4.0  28343.0
3     Toyota  White       154365.0    4.0  13434.0
4     Nissan   Blue       181577.0    3.0  14043.0
..       ...    ...            ...    ...      ...
995   Toyota  Black        35820.0    4.0  32042.0
996  missing  White       155144.0    3.0   5716.0
997   Nissan   Blue        66604.0    4.0  31570.0
998    Honda  White       215883.0    4.0   4001.0
999   Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [37]:
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [38]:
car_sales_missing.dropna(inplace=True)

In [39]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [40]:
car_sales_missing.size, car_sales_missing.shape

(4750, (950, 5))

### So now we have 950 rows and 5 columns. Although we can not work with missing labels

In [41]:
car_sales_missing.info()

<class 'pandas.DataFrame'>
Index: 950 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           950 non-null    str
 1   Colour         950 non-null    str
 2   Odometer (KM)  950 non-null    float64
 3   Doors          950 non-null    float64
 4   Price          950 non-null    float64
dtypes: float64(3), str(2)
memory usage: 44.5 KB

In [42]:
# Now we have to convert the `String values to numerical ones`
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Now we have to define catagorical_features
catagorical_features = ["Make", "Colour"]

#Let's now define onehotencoder
one_hot = OneHotEncoder()
# Now create the columnTransformer
transformer = ColumnTransformer(
    transformers=[
        ("one_hot", one_hot, catagorical_features) #Ok so it should be inside a tuple
    ], remainder="passthrough")
# Fit and transform dataFrame
transtormed_car_sales = transformer.fit_transform(car_sales_missing)
# Finally view the data
transtormed_car_sales

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 3.54310e+04,
        4.00000e+00, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.92714e+05,
        5.00000e+00, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 8.47140e+04,
        4.00000e+00, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 6.66040e+04,
        4.00000e+00, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 2.15883e+05,
        4.00000e+00, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 2.48360e+05,
        4.00000e+00, 1.27320e+04]], shape=(950, 14))

In [43]:
pd.DataFrame(transtormed_car_sales).head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,35431.0,4.0,15323.0
1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,192714.0,5.0,19943.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,84714.0,4.0,28343.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,154365.0,4.0,13434.0
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,181577.0,3.0,14043.0

### Option 2: Fill the missing values with scikit learn

In [44]:
car_missing_data = pd.read_csv("data/car-sales-extended-missing-data.csv")
car_missing_data.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [45]:
car_missing_data.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [46]:
car_missing_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           951 non-null    str
 1   Colour         950 non-null    str
 2   Odometer (KM)  950 non-null    float64
 3   Doors          950 non-null    float64
 4   Price          950 non-null    float64
dtypes: float64(3), str(2)
memory usage: 39.2 KB

In [47]:
# Now we want to remove the missing values from the label
car_missing_data.dropna(subset="Price", inplace=True)

In [48]:
car_missing_data.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [49]:
# Now let's try to convert these data in features and labels
X = car_missing_data.drop("Price", axis=1)

Y = car_missing_data["Price"]

In [50]:
X.head()

     Make Colour  Odometer (KM)  Doors
0   Honda  White        35431.0    4.0
1     BMW   Blue       192714.0    5.0
2   Honda  White        84714.0    4.0
3  Toyota  White       154365.0    4.0
4  Nissan   Blue       181577.0    3.0

In [51]:
# Now will see how to fill missing values with imputation and transformer
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Now we have to make imputation feature
cat_imputer = SimpleImputer(strategy="constant", fill_value="missing")
door_imputer = SimpleImputer(strategy="constant", fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

# Now we have to seperate the column's
cat_features = ["Make", "Colour"]
door_features = ["Doors"]
num_features = ["Odometer (KM)"]

# Now let's build the transformer
transformer = ColumnTransformer(
    transformers=[
        ("cat_imputer", cat_imputer, cat_features),
        ("door_imputer", door_imputer, door_features),
        ("num_imputer", num_imputer, num_features)
])

# Now we have to transform the data
x_transformed = transformer.fit_transform(X)
x_transformed

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], shape=(950, 4), dtype=object)

In [52]:
car_sales_filled = pd.DataFrame(x_transformed, columns=["Make", "Colour", "Doors", "Odometer (KM)"])
car_sales_filled.head()

     Make Colour Doors Odometer (KM)
0   Honda  White   4.0       35431.0
1     BMW   Blue   5.0      192714.0
2   Honda  White   4.0       84714.0
3  Toyota  White   4.0      154365.0
4  Nissan   Blue   3.0      181577.0

In [53]:
car_sales_filled.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [54]:
# Now we have to convert these values into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Now we have to define the features we want to convert into numbers
feature_columns = ["Make", "Colour"]

# We have to define the encoder also
one_hot = OneHotEncoder()

# Now we have to define the transformer
transformer = ColumnTransformer(
    transformers=[
        ("one_hot", one_hot, feature_columns)
    ],
    remainder="passthrough"
)

# Now we have to transform our data
x_transformed = transformer.fit_transform(car_sales_filled)
x_transformed

array([[0.0, 1.0, 0.0, ..., 0.0, 4.0, 35431.0],
       [1.0, 0.0, 0.0, ..., 0.0, 5.0, 192714.0],
       [0.0, 1.0, 0.0, ..., 0.0, 4.0, 84714.0],
       ...,
       [0.0, 0.0, 1.0, ..., 0.0, 4.0, 66604.0],
       [0.0, 1.0, 0.0, ..., 0.0, 4.0, 215883.0],
       [0.0, 0.0, 0.0, ..., 0.0, 4.0, 248360.0]],
      shape=(950, 13), dtype=object)

In [55]:
# Now let's fit a model...
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# Now we have to split the data into train and test
x_train, x_test, y_train, y_test = train_test_split(x_transformed, Y, test_size=0.2)

# Now we have to train our model
model = RandomForestRegressor()

model.fit(x_train, y_train)

model.score(x_test, y_test)

0.22108605075615018

## Now as our data is ready we will learn about how to choose the correct MODEL for our data.

We have to focus on some important things:
* Sklearn often reffers ML Models, algorithms as estimators
* Classification problems - predicting a catagory(heart disease or not)
  * Often we refer `clf` in code. which means classifire
* Regression problems - predicting a number (car price or average cost)

You can go here, you will be able to learn about different estimetors and how to choose them based on your current dataset: https://scikit-learn.org/stable/machine_learning_map.html

Type1: Regresson problem...

In [56]:
# Let's bring some real world datasets into work
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()

housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib:\nhttps://lib.stat.cmu.edu/datasets/houses.zip\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [57]:
housing_df = pd.DataFrame(housing["data"], columns=housing["feature_names"])
housing_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [58]:
housing_df["target"] = housing["target"]
housing_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [59]:
# Now we have to seperate Features and Labels
X = housing_df.drop("target", axis=1) # This is the features
Y = housing_df["target"] # This is the label

In [60]:
x.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [61]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [62]:
x.shape, x.size

((303, 13), 3939)

In [63]:
from sklearn.linear_model import Ridge
np.random.seed(42)
# Now we have selected the model 
model = Ridge()
# Now we have to split the data into train and test
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

# Now we will train our model and test the score
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.5351464847153693

### We can use different model for our dataset and find the best one

* Let's pick one of the `ensamble methods`
  * <b>Ensamble methods</b> are combination of `several algorithms/estimators`
  * Basically it gives the average result of all of the algorithms so that we get more efficiet presdictions.
  * It helps us to get more generalized results

If you want to study more about ensamble methods: https://scikit-learn.org/stable/modules/ensemble.html#random-forests-and-other-randomized-tree-ensembles

In [64]:
housing_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [65]:
from sklearn.ensemble import RandomForestRegressor
np.random.seed(42)
clf = RandomForestRegressor()

# splitting features and labels
X = housing_df.drop("target", axis=1)
Y = housing_df["target"]

# splitting our data to train and test
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.2)

# Now we have to fit the data to our model
clf.fit(x_train, y_train)
# getting the result
clf.score(x_test, y_test)

0.8058143916897114

### Why RandomForestClassifier is giving better result then Ridge ?

> So basically the RandomForest ensamble estimator gives predicction based on several base decision trees output.

- Decision trees are the building block of RandomForest. 
    - For classification task RandomForest predicts by `majority` voting among trees.
    - For regression task RandomForest predicts by making an `average` of the base trees predictions

Type2: Classification problems...

## Now as we have worked on regression problems, let's see how we can choose a model/estimator for classification problems.
- As a reminder <b>classification problems</b>: `Predicting a category`

In [66]:
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [67]:
heart_disease.shape, heart_disease.size

((303, 14), 4242)

In [68]:
from sklearn.svm import LinearSVC
clf = LinearSVC()
np.random.seed(42)
# Now let's define features and labels for our data
X = heart_disease.drop("target", axis=1)
Y = heart_disease["target"]

# Now we have to split our data to train and test
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

# Now we can start fitting out data with train x,y
clf.fit(x_train, y_train)

# Now let's score our data
clf.score(x_test, y_test)

0.8688524590163934

In [69]:
# Now it's time to cook with some ensamble modles
# Our hot favourate is RandomForestClassifier. Hopefully will get better result on this estimator
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier()
np.random.seed(42)
# Now we have to define features and labels
X = heart_disease.drop("target", axis=1)
Y = heart_disease["target"]

# Now we have to split our data to train test
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2)

# Now we have to fit our estimator with train dataset
rf_clf.fit(x_train, y_train)

# Let's see the result of our new model
rf_clf.score(x_test, y_test)

0.8524590163934426

## 3. Fit the model/Algorithm and use it to make prediction of our data
* 3.1 fitting the model

In [70]:
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [71]:
Y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

### So the main Idea is that we are giving our model some features and some labels and telling him to find patterns for which features it gives a corrosponding label.
In this case it's zero's and one's

### Now we have to make prediction in our test dataset. 
* Making predictions using:
    - `predict()` function
    - `predict_proba()` function

In [75]:
y_preds = rf_clf.predict(x_test) # We have to predict the data in our x features.
# It will give prediction in Y labels
y_preds

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [78]:
np.array(y_test) # Now we want to see the actual data

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [81]:
## So as we got prediction and actual data. we can compare them and measure the accuracy:
np.mean(y_preds == y_test).item() ## The .item() function removes the np.float64(0.8524590163934426) marks

0.8524590163934426

In [82]:
rf_clf.score(x_test, y_test)

0.8524590163934426

### Predicting data with `predict_proba()` 
- It actually defines the prediction in which basis it chooses one thing over another. In this case it's `0` & `1`
- Link: https://scikit-learn.org/stable/glossary.html#term-predict_proba

In [90]:
rf_clf.predict_proba(x_test)[:5] # Again we have to predict the laebls by recognizing the pattern of features

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [89]:
rf_clf.predict(x_test)[:5]

array([0, 1, 1, 0, 1])

In [91]:
housing_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [94]:
# The fun part is that we can make these predictions in regression problems as well
from sklearn.ensemble import RandomForestRegressor
# Set up random seed
np.random.seed(42)
# set up the model
rf_reg = RandomForestRegressor()

# splitting our data into features and labels
X = housing_df.drop("target", axis=1)
Y = housing_df["target"]

# Splitting data into test and train
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

# Now we have to fit our data to the model
rf_reg.fit(x_train, y_train)

# Predicting the labels
y_preds = rf_reg.predict(x_test)

In [95]:
y_preds[:5]

array([0.49275  , 0.76518  , 4.9235967, 2.55681  , 2.29356  ])

In [98]:
y_true = np.array(y_test)
y_true[:5]

array([0.477  , 0.458  , 5.00001, 2.186  , 2.78   ])

### `Mean Squared Error (MSE)` is a way to measure how wrong a model's predictions are compared to the actual values.
- It squers the error between actual value and predicted ones and avarages it all
- There are more: https://scikit-learn.org/stable/modules/model_evaluation.html

In [100]:
# Now we want to evaluate the prediction. Like how much accurate these predictions are?
from sklearn.metrics import mean_squared_error
mean_squared_error(y_true, y_preds)

0.2544625645749729

It's enough for today 🫡